#!/bin/bash
set -o errexit

main() {
  clear_tables
  create_users_table
  create_events_table
  create_cues_table
  grant_access
}

clear_tables() {
  psql -v ON_ERROR_EXIT=1 --username "$POSTGRES_USER" <<-EOSQL
    DROP TABLE IF EXISTS users, events;
EOSQL
}

create_users_table() {
  psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    \c $POSTGRES_DB;
    CREATE TABLE users (
      id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      uid VARCHAR(128) not null UNIQUE,
      suri VARCHAR(128) not null UNIQUE,
      display_name VARCHAR(64) not null,
      is_active BOOLEAN,
      evid VARCHAR(128),
      is_host BOOLEAN,
      joined_at TIMESTAMP
    );
EOSQL
}

create_events_table() {
  psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    \c $POSTGRES_DB;
    CREATE_TABLE events (
      id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      evid VARCHAR(128) not null UNIQUE,
      name VARCHAR(64) not null UNIQUE,
      attendees VARCHAR[],
      created_at TIMESTAMP,
      ended_at TIMESTAMP
    );
EOSQL
}

grant_access() {
  psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $POSTGRES_USER;
EOSQL
}
