version: '3.5'
services:
  openresty:
    container_name: openresty
    build: openresty
    ports:
      - 80:80
  auth:
    build: auth
    container_name: auth
    expose:
      - 4180
  srvsptfy:
    build: srvsptfy
    container_name: srvsptfy
    expose:
      - 10101
  cuesite:
    build: cuesite
    container_name: cuesite
    expose:
      - 10001
volumes:
  pgdata:
