// Code generated by protoc-gen-twirp v5.3.0, DO NOT EDIT.
// source: sptfyapi.proto

/*
Package sptfyapi is a generated twirp stub package.
This code was generated with github.com/twitchtv/twirp/protoc-gen-twirp v5.3.0.

It is generated from these files:
	sptfyapi.proto
*/
package sptfyapi

import bytes "bytes"
import strings "strings"
import context "context"
import fmt "fmt"
import ioutil "io/ioutil"
import http "net/http"

import jsonpb "github.com/golang/protobuf/jsonpb"
import proto "github.com/golang/protobuf/proto"
import twirp "github.com/twitchtv/twirp"
import ctxsetters "github.com/twitchtv/twirp/ctxsetters"

// Imports only used by utility functions:
import io "io"
import strconv "strconv"
import json "encoding/json"
import url "net/url"

// =====================
// InfoService Interface
// =====================

type InfoService interface {
	Info(context.Context, *InfoRequest) (*InfoResponse, error)
}

// ===========================
// InfoService Protobuf Client
// ===========================

type infoServiceProtobufClient struct {
	client HTTPClient
	urls   [1]string
}

// NewInfoServiceProtobufClient creates a Protobuf client that implements the InfoService interface.
// It communicates using Protobuf and can be configured with a custom HTTPClient.
func NewInfoServiceProtobufClient(addr string, client HTTPClient) InfoService {
	prefix := urlBase(addr) + InfoServicePathPrefix
	urls := [1]string{
		prefix + "Info",
	}
	if httpClient, ok := client.(*http.Client); ok {
		return &infoServiceProtobufClient{
			client: withoutRedirects(httpClient),
			urls:   urls,
		}
	}
	return &infoServiceProtobufClient{
		client: client,
		urls:   urls,
	}
}

func (c *infoServiceProtobufClient) Info(ctx context.Context, in *InfoRequest) (*InfoResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "sptfyapi")
	ctx = ctxsetters.WithServiceName(ctx, "InfoService")
	ctx = ctxsetters.WithMethodName(ctx, "Info")
	out := new(InfoResponse)
	err := doProtobufRequest(ctx, c.client, c.urls[0], in, out)
	return out, err
}

// =======================
// InfoService JSON Client
// =======================

type infoServiceJSONClient struct {
	client HTTPClient
	urls   [1]string
}

// NewInfoServiceJSONClient creates a JSON client that implements the InfoService interface.
// It communicates using JSON and can be configured with a custom HTTPClient.
func NewInfoServiceJSONClient(addr string, client HTTPClient) InfoService {
	prefix := urlBase(addr) + InfoServicePathPrefix
	urls := [1]string{
		prefix + "Info",
	}
	if httpClient, ok := client.(*http.Client); ok {
		return &infoServiceJSONClient{
			client: withoutRedirects(httpClient),
			urls:   urls,
		}
	}
	return &infoServiceJSONClient{
		client: client,
		urls:   urls,
	}
}

func (c *infoServiceJSONClient) Info(ctx context.Context, in *InfoRequest) (*InfoResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "sptfyapi")
	ctx = ctxsetters.WithServiceName(ctx, "InfoService")
	ctx = ctxsetters.WithMethodName(ctx, "Info")
	out := new(InfoResponse)
	err := doJSONRequest(ctx, c.client, c.urls[0], in, out)
	return out, err
}

// ==========================
// InfoService Server Handler
// ==========================

type infoServiceServer struct {
	InfoService
	hooks *twirp.ServerHooks
}

func NewInfoServiceServer(svc InfoService, hooks *twirp.ServerHooks) TwirpServer {
	return &infoServiceServer{
		InfoService: svc,
		hooks:       hooks,
	}
}

// writeError writes an HTTP response with a valid Twirp error format, and triggers hooks.
// If err is not a twirp.Error, it will get wrapped with twirp.InternalErrorWith(err)
func (s *infoServiceServer) writeError(ctx context.Context, resp http.ResponseWriter, err error) {
	writeError(ctx, resp, err, s.hooks)
}

// InfoServicePathPrefix is used for all URL paths on a twirp InfoService server.
// Requests are always: POST InfoServicePathPrefix/method
// It can be used in an HTTP mux to route twirp requests along with non-twirp requests on other routes.
const InfoServicePathPrefix = "/twirp/sptfyapi.InfoService/"

func (s *infoServiceServer) ServeHTTP(resp http.ResponseWriter, req *http.Request) {
	ctx := req.Context()
	ctx = ctxsetters.WithPackageName(ctx, "sptfyapi")
	ctx = ctxsetters.WithServiceName(ctx, "InfoService")
	ctx = ctxsetters.WithResponseWriter(ctx, resp)

	var err error
	ctx, err = callRequestReceived(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	if req.Method != "POST" {
		msg := fmt.Sprintf("unsupported method %q (only POST is allowed)", req.Method)
		err = badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, err)
		return
	}

	switch req.URL.Path {
	case "/twirp/sptfyapi.InfoService/Info":
		s.serveInfo(ctx, resp, req)
		return
	default:
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		err = badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, err)
		return
	}
}

func (s *infoServiceServer) serveInfo(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveInfoJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveInfoProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *infoServiceServer) serveInfoJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "Info")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	reqContent := new(InfoRequest)
	unmarshaler := jsonpb.Unmarshaler{AllowUnknownFields: true}
	if err = unmarshaler.Unmarshal(req.Body, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request json")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *InfoResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.Info(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *InfoResponse and nil error while calling Info. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	var buf bytes.Buffer
	marshaler := &jsonpb.Marshaler{OrigName: true}
	if err = marshaler.Marshal(&buf, respContent); err != nil {
		err = wrapErr(err, "failed to marshal json response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.WriteHeader(http.StatusOK)

	respBytes := buf.Bytes()
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *infoServiceServer) serveInfoProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "Info")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		err = wrapErr(err, "failed to read request body")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}
	reqContent := new(InfoRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request proto")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *InfoResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.Info(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *InfoResponse and nil error while calling Info. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		err = wrapErr(err, "failed to marshal proto response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *infoServiceServer) ServiceDescriptor() ([]byte, int) {
	return twirpFileDescriptor0, 0
}

func (s *infoServiceServer) ProtocGenTwirpVersion() string {
	return "v5.3.0"
}

// =====================
// AuthService Interface
// =====================

type AuthService interface {
	Auth(context.Context, *AuthRequest) (*AuthResponse, error)
}

// ===========================
// AuthService Protobuf Client
// ===========================

type authServiceProtobufClient struct {
	client HTTPClient
	urls   [1]string
}

// NewAuthServiceProtobufClient creates a Protobuf client that implements the AuthService interface.
// It communicates using Protobuf and can be configured with a custom HTTPClient.
func NewAuthServiceProtobufClient(addr string, client HTTPClient) AuthService {
	prefix := urlBase(addr) + AuthServicePathPrefix
	urls := [1]string{
		prefix + "Auth",
	}
	if httpClient, ok := client.(*http.Client); ok {
		return &authServiceProtobufClient{
			client: withoutRedirects(httpClient),
			urls:   urls,
		}
	}
	return &authServiceProtobufClient{
		client: client,
		urls:   urls,
	}
}

func (c *authServiceProtobufClient) Auth(ctx context.Context, in *AuthRequest) (*AuthResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "sptfyapi")
	ctx = ctxsetters.WithServiceName(ctx, "AuthService")
	ctx = ctxsetters.WithMethodName(ctx, "Auth")
	out := new(AuthResponse)
	err := doProtobufRequest(ctx, c.client, c.urls[0], in, out)
	return out, err
}

// =======================
// AuthService JSON Client
// =======================

type authServiceJSONClient struct {
	client HTTPClient
	urls   [1]string
}

// NewAuthServiceJSONClient creates a JSON client that implements the AuthService interface.
// It communicates using JSON and can be configured with a custom HTTPClient.
func NewAuthServiceJSONClient(addr string, client HTTPClient) AuthService {
	prefix := urlBase(addr) + AuthServicePathPrefix
	urls := [1]string{
		prefix + "Auth",
	}
	if httpClient, ok := client.(*http.Client); ok {
		return &authServiceJSONClient{
			client: withoutRedirects(httpClient),
			urls:   urls,
		}
	}
	return &authServiceJSONClient{
		client: client,
		urls:   urls,
	}
}

func (c *authServiceJSONClient) Auth(ctx context.Context, in *AuthRequest) (*AuthResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "sptfyapi")
	ctx = ctxsetters.WithServiceName(ctx, "AuthService")
	ctx = ctxsetters.WithMethodName(ctx, "Auth")
	out := new(AuthResponse)
	err := doJSONRequest(ctx, c.client, c.urls[0], in, out)
	return out, err
}

// ==========================
// AuthService Server Handler
// ==========================

type authServiceServer struct {
	AuthService
	hooks *twirp.ServerHooks
}

func NewAuthServiceServer(svc AuthService, hooks *twirp.ServerHooks) TwirpServer {
	return &authServiceServer{
		AuthService: svc,
		hooks:       hooks,
	}
}

// writeError writes an HTTP response with a valid Twirp error format, and triggers hooks.
// If err is not a twirp.Error, it will get wrapped with twirp.InternalErrorWith(err)
func (s *authServiceServer) writeError(ctx context.Context, resp http.ResponseWriter, err error) {
	writeError(ctx, resp, err, s.hooks)
}

// AuthServicePathPrefix is used for all URL paths on a twirp AuthService server.
// Requests are always: POST AuthServicePathPrefix/method
// It can be used in an HTTP mux to route twirp requests along with non-twirp requests on other routes.
const AuthServicePathPrefix = "/twirp/sptfyapi.AuthService/"

func (s *authServiceServer) ServeHTTP(resp http.ResponseWriter, req *http.Request) {
	ctx := req.Context()
	ctx = ctxsetters.WithPackageName(ctx, "sptfyapi")
	ctx = ctxsetters.WithServiceName(ctx, "AuthService")
	ctx = ctxsetters.WithResponseWriter(ctx, resp)

	var err error
	ctx, err = callRequestReceived(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	if req.Method != "POST" {
		msg := fmt.Sprintf("unsupported method %q (only POST is allowed)", req.Method)
		err = badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, err)
		return
	}

	switch req.URL.Path {
	case "/twirp/sptfyapi.AuthService/Auth":
		s.serveAuth(ctx, resp, req)
		return
	default:
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		err = badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, err)
		return
	}
}

func (s *authServiceServer) serveAuth(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveAuthJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveAuthProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *authServiceServer) serveAuthJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "Auth")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	reqContent := new(AuthRequest)
	unmarshaler := jsonpb.Unmarshaler{AllowUnknownFields: true}
	if err = unmarshaler.Unmarshal(req.Body, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request json")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *AuthResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.Auth(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *AuthResponse and nil error while calling Auth. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	var buf bytes.Buffer
	marshaler := &jsonpb.Marshaler{OrigName: true}
	if err = marshaler.Marshal(&buf, respContent); err != nil {
		err = wrapErr(err, "failed to marshal json response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.WriteHeader(http.StatusOK)

	respBytes := buf.Bytes()
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *authServiceServer) serveAuthProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "Auth")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		err = wrapErr(err, "failed to read request body")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}
	reqContent := new(AuthRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request proto")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *AuthResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.Auth(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *AuthResponse and nil error while calling Auth. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		err = wrapErr(err, "failed to marshal proto response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *authServiceServer) ServiceDescriptor() ([]byte, int) {
	return twirpFileDescriptor0, 1
}

func (s *authServiceServer) ProtocGenTwirpVersion() string {
	return "v5.3.0"
}

// =============================
// PlaybackNextService Interface
// =============================

type PlaybackNextService interface {
	PlaybackNext(context.Context, *PlaybackNextRequest) (*PlaybackNextResponse, error)
}

// ===================================
// PlaybackNextService Protobuf Client
// ===================================

type playbackNextServiceProtobufClient struct {
	client HTTPClient
	urls   [1]string
}

// NewPlaybackNextServiceProtobufClient creates a Protobuf client that implements the PlaybackNextService interface.
// It communicates using Protobuf and can be configured with a custom HTTPClient.
func NewPlaybackNextServiceProtobufClient(addr string, client HTTPClient) PlaybackNextService {
	prefix := urlBase(addr) + PlaybackNextServicePathPrefix
	urls := [1]string{
		prefix + "PlaybackNext",
	}
	if httpClient, ok := client.(*http.Client); ok {
		return &playbackNextServiceProtobufClient{
			client: withoutRedirects(httpClient),
			urls:   urls,
		}
	}
	return &playbackNextServiceProtobufClient{
		client: client,
		urls:   urls,
	}
}

func (c *playbackNextServiceProtobufClient) PlaybackNext(ctx context.Context, in *PlaybackNextRequest) (*PlaybackNextResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "sptfyapi")
	ctx = ctxsetters.WithServiceName(ctx, "PlaybackNextService")
	ctx = ctxsetters.WithMethodName(ctx, "PlaybackNext")
	out := new(PlaybackNextResponse)
	err := doProtobufRequest(ctx, c.client, c.urls[0], in, out)
	return out, err
}

// ===============================
// PlaybackNextService JSON Client
// ===============================

type playbackNextServiceJSONClient struct {
	client HTTPClient
	urls   [1]string
}

// NewPlaybackNextServiceJSONClient creates a JSON client that implements the PlaybackNextService interface.
// It communicates using JSON and can be configured with a custom HTTPClient.
func NewPlaybackNextServiceJSONClient(addr string, client HTTPClient) PlaybackNextService {
	prefix := urlBase(addr) + PlaybackNextServicePathPrefix
	urls := [1]string{
		prefix + "PlaybackNext",
	}
	if httpClient, ok := client.(*http.Client); ok {
		return &playbackNextServiceJSONClient{
			client: withoutRedirects(httpClient),
			urls:   urls,
		}
	}
	return &playbackNextServiceJSONClient{
		client: client,
		urls:   urls,
	}
}

func (c *playbackNextServiceJSONClient) PlaybackNext(ctx context.Context, in *PlaybackNextRequest) (*PlaybackNextResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "sptfyapi")
	ctx = ctxsetters.WithServiceName(ctx, "PlaybackNextService")
	ctx = ctxsetters.WithMethodName(ctx, "PlaybackNext")
	out := new(PlaybackNextResponse)
	err := doJSONRequest(ctx, c.client, c.urls[0], in, out)
	return out, err
}

// ==================================
// PlaybackNextService Server Handler
// ==================================

type playbackNextServiceServer struct {
	PlaybackNextService
	hooks *twirp.ServerHooks
}

func NewPlaybackNextServiceServer(svc PlaybackNextService, hooks *twirp.ServerHooks) TwirpServer {
	return &playbackNextServiceServer{
		PlaybackNextService: svc,
		hooks:               hooks,
	}
}

// writeError writes an HTTP response with a valid Twirp error format, and triggers hooks.
// If err is not a twirp.Error, it will get wrapped with twirp.InternalErrorWith(err)
func (s *playbackNextServiceServer) writeError(ctx context.Context, resp http.ResponseWriter, err error) {
	writeError(ctx, resp, err, s.hooks)
}

// PlaybackNextServicePathPrefix is used for all URL paths on a twirp PlaybackNextService server.
// Requests are always: POST PlaybackNextServicePathPrefix/method
// It can be used in an HTTP mux to route twirp requests along with non-twirp requests on other routes.
const PlaybackNextServicePathPrefix = "/twirp/sptfyapi.PlaybackNextService/"

func (s *playbackNextServiceServer) ServeHTTP(resp http.ResponseWriter, req *http.Request) {
	ctx := req.Context()
	ctx = ctxsetters.WithPackageName(ctx, "sptfyapi")
	ctx = ctxsetters.WithServiceName(ctx, "PlaybackNextService")
	ctx = ctxsetters.WithResponseWriter(ctx, resp)

	var err error
	ctx, err = callRequestReceived(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	if req.Method != "POST" {
		msg := fmt.Sprintf("unsupported method %q (only POST is allowed)", req.Method)
		err = badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, err)
		return
	}

	switch req.URL.Path {
	case "/twirp/sptfyapi.PlaybackNextService/PlaybackNext":
		s.servePlaybackNext(ctx, resp, req)
		return
	default:
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		err = badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, err)
		return
	}
}

func (s *playbackNextServiceServer) servePlaybackNext(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.servePlaybackNextJSON(ctx, resp, req)
	case "application/protobuf":
		s.servePlaybackNextProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *playbackNextServiceServer) servePlaybackNextJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "PlaybackNext")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	reqContent := new(PlaybackNextRequest)
	unmarshaler := jsonpb.Unmarshaler{AllowUnknownFields: true}
	if err = unmarshaler.Unmarshal(req.Body, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request json")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *PlaybackNextResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.PlaybackNext(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *PlaybackNextResponse and nil error while calling PlaybackNext. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	var buf bytes.Buffer
	marshaler := &jsonpb.Marshaler{OrigName: true}
	if err = marshaler.Marshal(&buf, respContent); err != nil {
		err = wrapErr(err, "failed to marshal json response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.WriteHeader(http.StatusOK)

	respBytes := buf.Bytes()
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *playbackNextServiceServer) servePlaybackNextProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "PlaybackNext")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		err = wrapErr(err, "failed to read request body")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}
	reqContent := new(PlaybackNextRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request proto")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *PlaybackNextResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.PlaybackNext(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *PlaybackNextResponse and nil error while calling PlaybackNext. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		err = wrapErr(err, "failed to marshal proto response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *playbackNextServiceServer) ServiceDescriptor() ([]byte, int) {
	return twirpFileDescriptor0, 2
}

func (s *playbackNextServiceServer) ProtocGenTwirpVersion() string {
	return "v5.3.0"
}

// =============================
// PlaybackPlayService Interface
// =============================

type PlaybackPlayService interface {
	PlaybackPlay(context.Context, *PlaybackPlayRequest) (*PlaybackPlayResponse, error)
}

// ===================================
// PlaybackPlayService Protobuf Client
// ===================================

type playbackPlayServiceProtobufClient struct {
	client HTTPClient
	urls   [1]string
}

// NewPlaybackPlayServiceProtobufClient creates a Protobuf client that implements the PlaybackPlayService interface.
// It communicates using Protobuf and can be configured with a custom HTTPClient.
func NewPlaybackPlayServiceProtobufClient(addr string, client HTTPClient) PlaybackPlayService {
	prefix := urlBase(addr) + PlaybackPlayServicePathPrefix
	urls := [1]string{
		prefix + "PlaybackPlay",
	}
	if httpClient, ok := client.(*http.Client); ok {
		return &playbackPlayServiceProtobufClient{
			client: withoutRedirects(httpClient),
			urls:   urls,
		}
	}
	return &playbackPlayServiceProtobufClient{
		client: client,
		urls:   urls,
	}
}

func (c *playbackPlayServiceProtobufClient) PlaybackPlay(ctx context.Context, in *PlaybackPlayRequest) (*PlaybackPlayResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "sptfyapi")
	ctx = ctxsetters.WithServiceName(ctx, "PlaybackPlayService")
	ctx = ctxsetters.WithMethodName(ctx, "PlaybackPlay")
	out := new(PlaybackPlayResponse)
	err := doProtobufRequest(ctx, c.client, c.urls[0], in, out)
	return out, err
}

// ===============================
// PlaybackPlayService JSON Client
// ===============================

type playbackPlayServiceJSONClient struct {
	client HTTPClient
	urls   [1]string
}

// NewPlaybackPlayServiceJSONClient creates a JSON client that implements the PlaybackPlayService interface.
// It communicates using JSON and can be configured with a custom HTTPClient.
func NewPlaybackPlayServiceJSONClient(addr string, client HTTPClient) PlaybackPlayService {
	prefix := urlBase(addr) + PlaybackPlayServicePathPrefix
	urls := [1]string{
		prefix + "PlaybackPlay",
	}
	if httpClient, ok := client.(*http.Client); ok {
		return &playbackPlayServiceJSONClient{
			client: withoutRedirects(httpClient),
			urls:   urls,
		}
	}
	return &playbackPlayServiceJSONClient{
		client: client,
		urls:   urls,
	}
}

func (c *playbackPlayServiceJSONClient) PlaybackPlay(ctx context.Context, in *PlaybackPlayRequest) (*PlaybackPlayResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "sptfyapi")
	ctx = ctxsetters.WithServiceName(ctx, "PlaybackPlayService")
	ctx = ctxsetters.WithMethodName(ctx, "PlaybackPlay")
	out := new(PlaybackPlayResponse)
	err := doJSONRequest(ctx, c.client, c.urls[0], in, out)
	return out, err
}

// ==================================
// PlaybackPlayService Server Handler
// ==================================

type playbackPlayServiceServer struct {
	PlaybackPlayService
	hooks *twirp.ServerHooks
}

func NewPlaybackPlayServiceServer(svc PlaybackPlayService, hooks *twirp.ServerHooks) TwirpServer {
	return &playbackPlayServiceServer{
		PlaybackPlayService: svc,
		hooks:               hooks,
	}
}

// writeError writes an HTTP response with a valid Twirp error format, and triggers hooks.
// If err is not a twirp.Error, it will get wrapped with twirp.InternalErrorWith(err)
func (s *playbackPlayServiceServer) writeError(ctx context.Context, resp http.ResponseWriter, err error) {
	writeError(ctx, resp, err, s.hooks)
}

// PlaybackPlayServicePathPrefix is used for all URL paths on a twirp PlaybackPlayService server.
// Requests are always: POST PlaybackPlayServicePathPrefix/method
// It can be used in an HTTP mux to route twirp requests along with non-twirp requests on other routes.
const PlaybackPlayServicePathPrefix = "/twirp/sptfyapi.PlaybackPlayService/"

func (s *playbackPlayServiceServer) ServeHTTP(resp http.ResponseWriter, req *http.Request) {
	ctx := req.Context()
	ctx = ctxsetters.WithPackageName(ctx, "sptfyapi")
	ctx = ctxsetters.WithServiceName(ctx, "PlaybackPlayService")
	ctx = ctxsetters.WithResponseWriter(ctx, resp)

	var err error
	ctx, err = callRequestReceived(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	if req.Method != "POST" {
		msg := fmt.Sprintf("unsupported method %q (only POST is allowed)", req.Method)
		err = badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, err)
		return
	}

	switch req.URL.Path {
	case "/twirp/sptfyapi.PlaybackPlayService/PlaybackPlay":
		s.servePlaybackPlay(ctx, resp, req)
		return
	default:
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		err = badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, err)
		return
	}
}

func (s *playbackPlayServiceServer) servePlaybackPlay(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.servePlaybackPlayJSON(ctx, resp, req)
	case "application/protobuf":
		s.servePlaybackPlayProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *playbackPlayServiceServer) servePlaybackPlayJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "PlaybackPlay")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	reqContent := new(PlaybackPlayRequest)
	unmarshaler := jsonpb.Unmarshaler{AllowUnknownFields: true}
	if err = unmarshaler.Unmarshal(req.Body, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request json")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *PlaybackPlayResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.PlaybackPlay(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *PlaybackPlayResponse and nil error while calling PlaybackPlay. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	var buf bytes.Buffer
	marshaler := &jsonpb.Marshaler{OrigName: true}
	if err = marshaler.Marshal(&buf, respContent); err != nil {
		err = wrapErr(err, "failed to marshal json response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.WriteHeader(http.StatusOK)

	respBytes := buf.Bytes()
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *playbackPlayServiceServer) servePlaybackPlayProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "PlaybackPlay")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		err = wrapErr(err, "failed to read request body")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}
	reqContent := new(PlaybackPlayRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request proto")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *PlaybackPlayResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.PlaybackPlay(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *PlaybackPlayResponse and nil error while calling PlaybackPlay. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		err = wrapErr(err, "failed to marshal proto response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *playbackPlayServiceServer) ServiceDescriptor() ([]byte, int) {
	return twirpFileDescriptor0, 3
}

func (s *playbackPlayServiceServer) ProtocGenTwirpVersion() string {
	return "v5.3.0"
}

// ==============================
// PlaybackPauseService Interface
// ==============================

type PlaybackPauseService interface {
	PlaybackPause(context.Context, *PlaybackPauseRequest) (*PlaybackPauseResponse, error)
}

// ====================================
// PlaybackPauseService Protobuf Client
// ====================================

type playbackPauseServiceProtobufClient struct {
	client HTTPClient
	urls   [1]string
}

// NewPlaybackPauseServiceProtobufClient creates a Protobuf client that implements the PlaybackPauseService interface.
// It communicates using Protobuf and can be configured with a custom HTTPClient.
func NewPlaybackPauseServiceProtobufClient(addr string, client HTTPClient) PlaybackPauseService {
	prefix := urlBase(addr) + PlaybackPauseServicePathPrefix
	urls := [1]string{
		prefix + "PlaybackPause",
	}
	if httpClient, ok := client.(*http.Client); ok {
		return &playbackPauseServiceProtobufClient{
			client: withoutRedirects(httpClient),
			urls:   urls,
		}
	}
	return &playbackPauseServiceProtobufClient{
		client: client,
		urls:   urls,
	}
}

func (c *playbackPauseServiceProtobufClient) PlaybackPause(ctx context.Context, in *PlaybackPauseRequest) (*PlaybackPauseResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "sptfyapi")
	ctx = ctxsetters.WithServiceName(ctx, "PlaybackPauseService")
	ctx = ctxsetters.WithMethodName(ctx, "PlaybackPause")
	out := new(PlaybackPauseResponse)
	err := doProtobufRequest(ctx, c.client, c.urls[0], in, out)
	return out, err
}

// ================================
// PlaybackPauseService JSON Client
// ================================

type playbackPauseServiceJSONClient struct {
	client HTTPClient
	urls   [1]string
}

// NewPlaybackPauseServiceJSONClient creates a JSON client that implements the PlaybackPauseService interface.
// It communicates using JSON and can be configured with a custom HTTPClient.
func NewPlaybackPauseServiceJSONClient(addr string, client HTTPClient) PlaybackPauseService {
	prefix := urlBase(addr) + PlaybackPauseServicePathPrefix
	urls := [1]string{
		prefix + "PlaybackPause",
	}
	if httpClient, ok := client.(*http.Client); ok {
		return &playbackPauseServiceJSONClient{
			client: withoutRedirects(httpClient),
			urls:   urls,
		}
	}
	return &playbackPauseServiceJSONClient{
		client: client,
		urls:   urls,
	}
}

func (c *playbackPauseServiceJSONClient) PlaybackPause(ctx context.Context, in *PlaybackPauseRequest) (*PlaybackPauseResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "sptfyapi")
	ctx = ctxsetters.WithServiceName(ctx, "PlaybackPauseService")
	ctx = ctxsetters.WithMethodName(ctx, "PlaybackPause")
	out := new(PlaybackPauseResponse)
	err := doJSONRequest(ctx, c.client, c.urls[0], in, out)
	return out, err
}

// ===================================
// PlaybackPauseService Server Handler
// ===================================

type playbackPauseServiceServer struct {
	PlaybackPauseService
	hooks *twirp.ServerHooks
}

func NewPlaybackPauseServiceServer(svc PlaybackPauseService, hooks *twirp.ServerHooks) TwirpServer {
	return &playbackPauseServiceServer{
		PlaybackPauseService: svc,
		hooks:                hooks,
	}
}

// writeError writes an HTTP response with a valid Twirp error format, and triggers hooks.
// If err is not a twirp.Error, it will get wrapped with twirp.InternalErrorWith(err)
func (s *playbackPauseServiceServer) writeError(ctx context.Context, resp http.ResponseWriter, err error) {
	writeError(ctx, resp, err, s.hooks)
}

// PlaybackPauseServicePathPrefix is used for all URL paths on a twirp PlaybackPauseService server.
// Requests are always: POST PlaybackPauseServicePathPrefix/method
// It can be used in an HTTP mux to route twirp requests along with non-twirp requests on other routes.
const PlaybackPauseServicePathPrefix = "/twirp/sptfyapi.PlaybackPauseService/"

func (s *playbackPauseServiceServer) ServeHTTP(resp http.ResponseWriter, req *http.Request) {
	ctx := req.Context()
	ctx = ctxsetters.WithPackageName(ctx, "sptfyapi")
	ctx = ctxsetters.WithServiceName(ctx, "PlaybackPauseService")
	ctx = ctxsetters.WithResponseWriter(ctx, resp)

	var err error
	ctx, err = callRequestReceived(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	if req.Method != "POST" {
		msg := fmt.Sprintf("unsupported method %q (only POST is allowed)", req.Method)
		err = badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, err)
		return
	}

	switch req.URL.Path {
	case "/twirp/sptfyapi.PlaybackPauseService/PlaybackPause":
		s.servePlaybackPause(ctx, resp, req)
		return
	default:
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		err = badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, err)
		return
	}
}

func (s *playbackPauseServiceServer) servePlaybackPause(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.servePlaybackPauseJSON(ctx, resp, req)
	case "application/protobuf":
		s.servePlaybackPauseProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *playbackPauseServiceServer) servePlaybackPauseJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "PlaybackPause")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	reqContent := new(PlaybackPauseRequest)
	unmarshaler := jsonpb.Unmarshaler{AllowUnknownFields: true}
	if err = unmarshaler.Unmarshal(req.Body, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request json")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *PlaybackPauseResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.PlaybackPause(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *PlaybackPauseResponse and nil error while calling PlaybackPause. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	var buf bytes.Buffer
	marshaler := &jsonpb.Marshaler{OrigName: true}
	if err = marshaler.Marshal(&buf, respContent); err != nil {
		err = wrapErr(err, "failed to marshal json response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.WriteHeader(http.StatusOK)

	respBytes := buf.Bytes()
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *playbackPauseServiceServer) servePlaybackPauseProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "PlaybackPause")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		err = wrapErr(err, "failed to read request body")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}
	reqContent := new(PlaybackPauseRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request proto")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *PlaybackPauseResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.PlaybackPause(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *PlaybackPauseResponse and nil error while calling PlaybackPause. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		err = wrapErr(err, "failed to marshal proto response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *playbackPauseServiceServer) ServiceDescriptor() ([]byte, int) {
	return twirpFileDescriptor0, 4
}

func (s *playbackPauseServiceServer) ProtocGenTwirpVersion() string {
	return "v5.3.0"
}

// ============================
// TrackSearchService Interface
// ============================

type TrackSearchService interface {
	SearchTrack(context.Context, *TrackSearchRequest) (*TrackSearchResponse, error)
}

// ==================================
// TrackSearchService Protobuf Client
// ==================================

type trackSearchServiceProtobufClient struct {
	client HTTPClient
	urls   [1]string
}

// NewTrackSearchServiceProtobufClient creates a Protobuf client that implements the TrackSearchService interface.
// It communicates using Protobuf and can be configured with a custom HTTPClient.
func NewTrackSearchServiceProtobufClient(addr string, client HTTPClient) TrackSearchService {
	prefix := urlBase(addr) + TrackSearchServicePathPrefix
	urls := [1]string{
		prefix + "SearchTrack",
	}
	if httpClient, ok := client.(*http.Client); ok {
		return &trackSearchServiceProtobufClient{
			client: withoutRedirects(httpClient),
			urls:   urls,
		}
	}
	return &trackSearchServiceProtobufClient{
		client: client,
		urls:   urls,
	}
}

func (c *trackSearchServiceProtobufClient) SearchTrack(ctx context.Context, in *TrackSearchRequest) (*TrackSearchResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "sptfyapi")
	ctx = ctxsetters.WithServiceName(ctx, "TrackSearchService")
	ctx = ctxsetters.WithMethodName(ctx, "SearchTrack")
	out := new(TrackSearchResponse)
	err := doProtobufRequest(ctx, c.client, c.urls[0], in, out)
	return out, err
}

// ==============================
// TrackSearchService JSON Client
// ==============================

type trackSearchServiceJSONClient struct {
	client HTTPClient
	urls   [1]string
}

// NewTrackSearchServiceJSONClient creates a JSON client that implements the TrackSearchService interface.
// It communicates using JSON and can be configured with a custom HTTPClient.
func NewTrackSearchServiceJSONClient(addr string, client HTTPClient) TrackSearchService {
	prefix := urlBase(addr) + TrackSearchServicePathPrefix
	urls := [1]string{
		prefix + "SearchTrack",
	}
	if httpClient, ok := client.(*http.Client); ok {
		return &trackSearchServiceJSONClient{
			client: withoutRedirects(httpClient),
			urls:   urls,
		}
	}
	return &trackSearchServiceJSONClient{
		client: client,
		urls:   urls,
	}
}

func (c *trackSearchServiceJSONClient) SearchTrack(ctx context.Context, in *TrackSearchRequest) (*TrackSearchResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "sptfyapi")
	ctx = ctxsetters.WithServiceName(ctx, "TrackSearchService")
	ctx = ctxsetters.WithMethodName(ctx, "SearchTrack")
	out := new(TrackSearchResponse)
	err := doJSONRequest(ctx, c.client, c.urls[0], in, out)
	return out, err
}

// =================================
// TrackSearchService Server Handler
// =================================

type trackSearchServiceServer struct {
	TrackSearchService
	hooks *twirp.ServerHooks
}

func NewTrackSearchServiceServer(svc TrackSearchService, hooks *twirp.ServerHooks) TwirpServer {
	return &trackSearchServiceServer{
		TrackSearchService: svc,
		hooks:              hooks,
	}
}

// writeError writes an HTTP response with a valid Twirp error format, and triggers hooks.
// If err is not a twirp.Error, it will get wrapped with twirp.InternalErrorWith(err)
func (s *trackSearchServiceServer) writeError(ctx context.Context, resp http.ResponseWriter, err error) {
	writeError(ctx, resp, err, s.hooks)
}

// TrackSearchServicePathPrefix is used for all URL paths on a twirp TrackSearchService server.
// Requests are always: POST TrackSearchServicePathPrefix/method
// It can be used in an HTTP mux to route twirp requests along with non-twirp requests on other routes.
const TrackSearchServicePathPrefix = "/twirp/sptfyapi.TrackSearchService/"

func (s *trackSearchServiceServer) ServeHTTP(resp http.ResponseWriter, req *http.Request) {
	ctx := req.Context()
	ctx = ctxsetters.WithPackageName(ctx, "sptfyapi")
	ctx = ctxsetters.WithServiceName(ctx, "TrackSearchService")
	ctx = ctxsetters.WithResponseWriter(ctx, resp)

	var err error
	ctx, err = callRequestReceived(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	if req.Method != "POST" {
		msg := fmt.Sprintf("unsupported method %q (only POST is allowed)", req.Method)
		err = badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, err)
		return
	}

	switch req.URL.Path {
	case "/twirp/sptfyapi.TrackSearchService/SearchTrack":
		s.serveSearchTrack(ctx, resp, req)
		return
	default:
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		err = badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, err)
		return
	}
}

func (s *trackSearchServiceServer) serveSearchTrack(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveSearchTrackJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveSearchTrackProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *trackSearchServiceServer) serveSearchTrackJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "SearchTrack")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	reqContent := new(TrackSearchRequest)
	unmarshaler := jsonpb.Unmarshaler{AllowUnknownFields: true}
	if err = unmarshaler.Unmarshal(req.Body, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request json")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *TrackSearchResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.SearchTrack(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *TrackSearchResponse and nil error while calling SearchTrack. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	var buf bytes.Buffer
	marshaler := &jsonpb.Marshaler{OrigName: true}
	if err = marshaler.Marshal(&buf, respContent); err != nil {
		err = wrapErr(err, "failed to marshal json response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.WriteHeader(http.StatusOK)

	respBytes := buf.Bytes()
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *trackSearchServiceServer) serveSearchTrackProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "SearchTrack")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		err = wrapErr(err, "failed to read request body")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}
	reqContent := new(TrackSearchRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request proto")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *TrackSearchResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.SearchTrack(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *TrackSearchResponse and nil error while calling SearchTrack. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		err = wrapErr(err, "failed to marshal proto response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *trackSearchServiceServer) ServiceDescriptor() ([]byte, int) {
	return twirpFileDescriptor0, 5
}

func (s *trackSearchServiceServer) ProtocGenTwirpVersion() string {
	return "v5.3.0"
}

// ============================
// AlbumSearchService Interface
// ============================

type AlbumSearchService interface {
	SearchAlbum(context.Context, *AlbumSearchRequest) (*AlbumSearchResponse, error)
}

// ==================================
// AlbumSearchService Protobuf Client
// ==================================

type albumSearchServiceProtobufClient struct {
	client HTTPClient
	urls   [1]string
}

// NewAlbumSearchServiceProtobufClient creates a Protobuf client that implements the AlbumSearchService interface.
// It communicates using Protobuf and can be configured with a custom HTTPClient.
func NewAlbumSearchServiceProtobufClient(addr string, client HTTPClient) AlbumSearchService {
	prefix := urlBase(addr) + AlbumSearchServicePathPrefix
	urls := [1]string{
		prefix + "SearchAlbum",
	}
	if httpClient, ok := client.(*http.Client); ok {
		return &albumSearchServiceProtobufClient{
			client: withoutRedirects(httpClient),
			urls:   urls,
		}
	}
	return &albumSearchServiceProtobufClient{
		client: client,
		urls:   urls,
	}
}

func (c *albumSearchServiceProtobufClient) SearchAlbum(ctx context.Context, in *AlbumSearchRequest) (*AlbumSearchResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "sptfyapi")
	ctx = ctxsetters.WithServiceName(ctx, "AlbumSearchService")
	ctx = ctxsetters.WithMethodName(ctx, "SearchAlbum")
	out := new(AlbumSearchResponse)
	err := doProtobufRequest(ctx, c.client, c.urls[0], in, out)
	return out, err
}

// ==============================
// AlbumSearchService JSON Client
// ==============================

type albumSearchServiceJSONClient struct {
	client HTTPClient
	urls   [1]string
}

// NewAlbumSearchServiceJSONClient creates a JSON client that implements the AlbumSearchService interface.
// It communicates using JSON and can be configured with a custom HTTPClient.
func NewAlbumSearchServiceJSONClient(addr string, client HTTPClient) AlbumSearchService {
	prefix := urlBase(addr) + AlbumSearchServicePathPrefix
	urls := [1]string{
		prefix + "SearchAlbum",
	}
	if httpClient, ok := client.(*http.Client); ok {
		return &albumSearchServiceJSONClient{
			client: withoutRedirects(httpClient),
			urls:   urls,
		}
	}
	return &albumSearchServiceJSONClient{
		client: client,
		urls:   urls,
	}
}

func (c *albumSearchServiceJSONClient) SearchAlbum(ctx context.Context, in *AlbumSearchRequest) (*AlbumSearchResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "sptfyapi")
	ctx = ctxsetters.WithServiceName(ctx, "AlbumSearchService")
	ctx = ctxsetters.WithMethodName(ctx, "SearchAlbum")
	out := new(AlbumSearchResponse)
	err := doJSONRequest(ctx, c.client, c.urls[0], in, out)
	return out, err
}

// =================================
// AlbumSearchService Server Handler
// =================================

type albumSearchServiceServer struct {
	AlbumSearchService
	hooks *twirp.ServerHooks
}

func NewAlbumSearchServiceServer(svc AlbumSearchService, hooks *twirp.ServerHooks) TwirpServer {
	return &albumSearchServiceServer{
		AlbumSearchService: svc,
		hooks:              hooks,
	}
}

// writeError writes an HTTP response with a valid Twirp error format, and triggers hooks.
// If err is not a twirp.Error, it will get wrapped with twirp.InternalErrorWith(err)
func (s *albumSearchServiceServer) writeError(ctx context.Context, resp http.ResponseWriter, err error) {
	writeError(ctx, resp, err, s.hooks)
}

// AlbumSearchServicePathPrefix is used for all URL paths on a twirp AlbumSearchService server.
// Requests are always: POST AlbumSearchServicePathPrefix/method
// It can be used in an HTTP mux to route twirp requests along with non-twirp requests on other routes.
const AlbumSearchServicePathPrefix = "/twirp/sptfyapi.AlbumSearchService/"

func (s *albumSearchServiceServer) ServeHTTP(resp http.ResponseWriter, req *http.Request) {
	ctx := req.Context()
	ctx = ctxsetters.WithPackageName(ctx, "sptfyapi")
	ctx = ctxsetters.WithServiceName(ctx, "AlbumSearchService")
	ctx = ctxsetters.WithResponseWriter(ctx, resp)

	var err error
	ctx, err = callRequestReceived(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	if req.Method != "POST" {
		msg := fmt.Sprintf("unsupported method %q (only POST is allowed)", req.Method)
		err = badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, err)
		return
	}

	switch req.URL.Path {
	case "/twirp/sptfyapi.AlbumSearchService/SearchAlbum":
		s.serveSearchAlbum(ctx, resp, req)
		return
	default:
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		err = badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, err)
		return
	}
}

func (s *albumSearchServiceServer) serveSearchAlbum(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveSearchAlbumJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveSearchAlbumProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *albumSearchServiceServer) serveSearchAlbumJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "SearchAlbum")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	reqContent := new(AlbumSearchRequest)
	unmarshaler := jsonpb.Unmarshaler{AllowUnknownFields: true}
	if err = unmarshaler.Unmarshal(req.Body, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request json")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *AlbumSearchResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.SearchAlbum(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *AlbumSearchResponse and nil error while calling SearchAlbum. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	var buf bytes.Buffer
	marshaler := &jsonpb.Marshaler{OrigName: true}
	if err = marshaler.Marshal(&buf, respContent); err != nil {
		err = wrapErr(err, "failed to marshal json response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.WriteHeader(http.StatusOK)

	respBytes := buf.Bytes()
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *albumSearchServiceServer) serveSearchAlbumProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "SearchAlbum")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		err = wrapErr(err, "failed to read request body")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}
	reqContent := new(AlbumSearchRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request proto")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *AlbumSearchResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.SearchAlbum(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *AlbumSearchResponse and nil error while calling SearchAlbum. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		err = wrapErr(err, "failed to marshal proto response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *albumSearchServiceServer) ServiceDescriptor() ([]byte, int) {
	return twirpFileDescriptor0, 6
}

func (s *albumSearchServiceServer) ProtocGenTwirpVersion() string {
	return "v5.3.0"
}

// =============================
// ArtistSearchService Interface
// =============================

type ArtistSearchService interface {
	SearchArtist(context.Context, *ArtistSearchRequest) (*AlbumSearchResponse, error)
}

// ===================================
// ArtistSearchService Protobuf Client
// ===================================

type artistSearchServiceProtobufClient struct {
	client HTTPClient
	urls   [1]string
}

// NewArtistSearchServiceProtobufClient creates a Protobuf client that implements the ArtistSearchService interface.
// It communicates using Protobuf and can be configured with a custom HTTPClient.
func NewArtistSearchServiceProtobufClient(addr string, client HTTPClient) ArtistSearchService {
	prefix := urlBase(addr) + ArtistSearchServicePathPrefix
	urls := [1]string{
		prefix + "SearchArtist",
	}
	if httpClient, ok := client.(*http.Client); ok {
		return &artistSearchServiceProtobufClient{
			client: withoutRedirects(httpClient),
			urls:   urls,
		}
	}
	return &artistSearchServiceProtobufClient{
		client: client,
		urls:   urls,
	}
}

func (c *artistSearchServiceProtobufClient) SearchArtist(ctx context.Context, in *ArtistSearchRequest) (*AlbumSearchResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "sptfyapi")
	ctx = ctxsetters.WithServiceName(ctx, "ArtistSearchService")
	ctx = ctxsetters.WithMethodName(ctx, "SearchArtist")
	out := new(AlbumSearchResponse)
	err := doProtobufRequest(ctx, c.client, c.urls[0], in, out)
	return out, err
}

// ===============================
// ArtistSearchService JSON Client
// ===============================

type artistSearchServiceJSONClient struct {
	client HTTPClient
	urls   [1]string
}

// NewArtistSearchServiceJSONClient creates a JSON client that implements the ArtistSearchService interface.
// It communicates using JSON and can be configured with a custom HTTPClient.
func NewArtistSearchServiceJSONClient(addr string, client HTTPClient) ArtistSearchService {
	prefix := urlBase(addr) + ArtistSearchServicePathPrefix
	urls := [1]string{
		prefix + "SearchArtist",
	}
	if httpClient, ok := client.(*http.Client); ok {
		return &artistSearchServiceJSONClient{
			client: withoutRedirects(httpClient),
			urls:   urls,
		}
	}
	return &artistSearchServiceJSONClient{
		client: client,
		urls:   urls,
	}
}

func (c *artistSearchServiceJSONClient) SearchArtist(ctx context.Context, in *ArtistSearchRequest) (*AlbumSearchResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "sptfyapi")
	ctx = ctxsetters.WithServiceName(ctx, "ArtistSearchService")
	ctx = ctxsetters.WithMethodName(ctx, "SearchArtist")
	out := new(AlbumSearchResponse)
	err := doJSONRequest(ctx, c.client, c.urls[0], in, out)
	return out, err
}

// ==================================
// ArtistSearchService Server Handler
// ==================================

type artistSearchServiceServer struct {
	ArtistSearchService
	hooks *twirp.ServerHooks
}

func NewArtistSearchServiceServer(svc ArtistSearchService, hooks *twirp.ServerHooks) TwirpServer {
	return &artistSearchServiceServer{
		ArtistSearchService: svc,
		hooks:               hooks,
	}
}

// writeError writes an HTTP response with a valid Twirp error format, and triggers hooks.
// If err is not a twirp.Error, it will get wrapped with twirp.InternalErrorWith(err)
func (s *artistSearchServiceServer) writeError(ctx context.Context, resp http.ResponseWriter, err error) {
	writeError(ctx, resp, err, s.hooks)
}

// ArtistSearchServicePathPrefix is used for all URL paths on a twirp ArtistSearchService server.
// Requests are always: POST ArtistSearchServicePathPrefix/method
// It can be used in an HTTP mux to route twirp requests along with non-twirp requests on other routes.
const ArtistSearchServicePathPrefix = "/twirp/sptfyapi.ArtistSearchService/"

func (s *artistSearchServiceServer) ServeHTTP(resp http.ResponseWriter, req *http.Request) {
	ctx := req.Context()
	ctx = ctxsetters.WithPackageName(ctx, "sptfyapi")
	ctx = ctxsetters.WithServiceName(ctx, "ArtistSearchService")
	ctx = ctxsetters.WithResponseWriter(ctx, resp)

	var err error
	ctx, err = callRequestReceived(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	if req.Method != "POST" {
		msg := fmt.Sprintf("unsupported method %q (only POST is allowed)", req.Method)
		err = badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, err)
		return
	}

	switch req.URL.Path {
	case "/twirp/sptfyapi.ArtistSearchService/SearchArtist":
		s.serveSearchArtist(ctx, resp, req)
		return
	default:
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		err = badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, err)
		return
	}
}

func (s *artistSearchServiceServer) serveSearchArtist(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveSearchArtistJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveSearchArtistProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *artistSearchServiceServer) serveSearchArtistJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "SearchArtist")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	reqContent := new(ArtistSearchRequest)
	unmarshaler := jsonpb.Unmarshaler{AllowUnknownFields: true}
	if err = unmarshaler.Unmarshal(req.Body, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request json")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *AlbumSearchResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.SearchArtist(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *AlbumSearchResponse and nil error while calling SearchArtist. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	var buf bytes.Buffer
	marshaler := &jsonpb.Marshaler{OrigName: true}
	if err = marshaler.Marshal(&buf, respContent); err != nil {
		err = wrapErr(err, "failed to marshal json response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.WriteHeader(http.StatusOK)

	respBytes := buf.Bytes()
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *artistSearchServiceServer) serveSearchArtistProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "SearchArtist")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		err = wrapErr(err, "failed to read request body")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}
	reqContent := new(ArtistSearchRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request proto")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *AlbumSearchResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.SearchArtist(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *AlbumSearchResponse and nil error while calling SearchArtist. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		err = wrapErr(err, "failed to marshal proto response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *artistSearchServiceServer) ServiceDescriptor() ([]byte, int) {
	return twirpFileDescriptor0, 7
}

func (s *artistSearchServiceServer) ProtocGenTwirpVersion() string {
	return "v5.3.0"
}

// =====
// Utils
// =====

// HTTPClient is the interface used by generated clients to send HTTP requests.
// It is fulfilled by *(net/http).Client, which is sufficient for most users.
// Users can provide their own implementation for special retry policies.
//
// HTTPClient implementations should not follow redirects. Redirects are
// automatically disabled if *(net/http).Client is passed to client
// constructors. See the withoutRedirects function in this file for more
// details.
type HTTPClient interface {
	Do(req *http.Request) (*http.Response, error)
}

// TwirpServer is the interface generated server structs will support: they're
// HTTP handlers with additional methods for accessing metadata about the
// service. Those accessors are a low-level API for building reflection tools.
// Most people can think of TwirpServers as just http.Handlers.
type TwirpServer interface {
	http.Handler
	// ServiceDescriptor returns gzipped bytes describing the .proto file that
	// this service was generated from. Once unzipped, the bytes can be
	// unmarshalled as a
	// github.com/golang/protobuf/protoc-gen-go/descriptor.FileDescriptorProto.
	//
	// The returned integer is the index of this particular service within that
	// FileDescriptorProto's 'Service' slice of ServiceDescriptorProtos. This is a
	// low-level field, expected to be used for reflection.
	ServiceDescriptor() ([]byte, int)
	// ProtocGenTwirpVersion is the semantic version string of the version of
	// twirp used to generate this file.
	ProtocGenTwirpVersion() string
}

// WriteError writes an HTTP response with a valid Twirp error format.
// If err is not a twirp.Error, it will get wrapped with twirp.InternalErrorWith(err)
func WriteError(resp http.ResponseWriter, err error) {
	writeError(context.Background(), resp, err, nil)
}

// writeError writes Twirp errors in the response and triggers hooks.
func writeError(ctx context.Context, resp http.ResponseWriter, err error, hooks *twirp.ServerHooks) {
	// Non-twirp errors are wrapped as Internal (default)
	twerr, ok := err.(twirp.Error)
	if !ok {
		twerr = twirp.InternalErrorWith(err)
	}

	statusCode := twirp.ServerHTTPStatusFromErrorCode(twerr.Code())
	ctx = ctxsetters.WithStatusCode(ctx, statusCode)
	ctx = callError(ctx, hooks, twerr)

	resp.Header().Set("Content-Type", "application/json") // Error responses are always JSON (instead of protobuf)
	resp.WriteHeader(statusCode)                          // HTTP response status code

	respBody := marshalErrorToJSON(twerr)
	_, writeErr := resp.Write(respBody)
	if writeErr != nil {
		// We have three options here. We could log the error, call the Error
		// hook, or just silently ignore the error.
		//
		// Logging is unacceptable because we don't have a user-controlled
		// logger; writing out to stderr without permission is too rude.
		//
		// Calling the Error hook would confuse users: it would mean the Error
		// hook got called twice for one request, which is likely to lead to
		// duplicated log messages and metrics, no matter how well we document
		// the behavior.
		//
		// Silently ignoring the error is our least-bad option. It's highly
		// likely that the connection is broken and the original 'err' says
		// so anyway.
		_ = writeErr
	}

	callResponseSent(ctx, hooks)
}

// urlBase helps ensure that addr specifies a scheme. If it is unparsable
// as a URL, it returns addr unchanged.
func urlBase(addr string) string {
	// If the addr specifies a scheme, use it. If not, default to
	// http. If url.Parse fails on it, return it unchanged.
	url, err := url.Parse(addr)
	if err != nil {
		return addr
	}
	if url.Scheme == "" {
		url.Scheme = "http"
	}
	return url.String()
}

// getCustomHTTPReqHeaders retrieves a copy of any headers that are set in
// a context through the twirp.WithHTTPRequestHeaders function.
// If there are no headers set, or if they have the wrong type, nil is returned.
func getCustomHTTPReqHeaders(ctx context.Context) http.Header {
	header, ok := twirp.HTTPRequestHeaders(ctx)
	if !ok || header == nil {
		return nil
	}
	copied := make(http.Header)
	for k, vv := range header {
		if vv == nil {
			copied[k] = nil
			continue
		}
		copied[k] = make([]string, len(vv))
		copy(copied[k], vv)
	}
	return copied
}

// newRequest makes an http.Request from a client, adding common headers.
func newRequest(ctx context.Context, url string, reqBody io.Reader, contentType string) (*http.Request, error) {
	req, err := http.NewRequest("POST", url, reqBody)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if customHeader := getCustomHTTPReqHeaders(ctx); customHeader != nil {
		req.Header = customHeader
	}
	req.Header.Set("Accept", contentType)
	req.Header.Set("Content-Type", contentType)
	req.Header.Set("Twirp-Version", "v5.3.0")
	return req, nil
}

// JSON serialization for errors
type twerrJSON struct {
	Code string            `json:"code"`
	Msg  string            `json:"msg"`
	Meta map[string]string `json:"meta,omitempty"`
}

// marshalErrorToJSON returns JSON from a twirp.Error, that can be used as HTTP error response body.
// If serialization fails, it will use a descriptive Internal error instead.
func marshalErrorToJSON(twerr twirp.Error) []byte {
	// make sure that msg is not too large
	msg := twerr.Msg()
	if len(msg) > 1e6 {
		msg = msg[:1e6]
	}

	tj := twerrJSON{
		Code: string(twerr.Code()),
		Msg:  msg,
		Meta: twerr.MetaMap(),
	}

	buf, err := json.Marshal(&tj)
	if err != nil {
		buf = []byte("{\"type\": \"" + twirp.Internal + "\", \"msg\": \"There was an error but it could not be serialized into JSON\"}") // fallback
	}

	return buf
}

// errorFromResponse builds a twirp.Error from a non-200 HTTP response.
// If the response has a valid serialized Twirp error, then it's returned.
// If not, the response status code is used to generate a similar twirp
// error. See twirpErrorFromIntermediary for more info on intermediary errors.
func errorFromResponse(resp *http.Response) twirp.Error {
	statusCode := resp.StatusCode
	statusText := http.StatusText(statusCode)

	if isHTTPRedirect(statusCode) {
		// Unexpected redirect: it must be an error from an intermediary.
		// Twirp clients don't follow redirects automatically, Twirp only handles
		// POST requests, redirects should only happen on GET and HEAD requests.
		location := resp.Header.Get("Location")
		msg := fmt.Sprintf("unexpected HTTP status code %d %q received, Location=%q", statusCode, statusText, location)
		return twirpErrorFromIntermediary(statusCode, msg, location)
	}

	respBodyBytes, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		return clientError("failed to read server error response body", err)
	}
	var tj twerrJSON
	if err := json.Unmarshal(respBodyBytes, &tj); err != nil {
		// Invalid JSON response; it must be an error from an intermediary.
		msg := fmt.Sprintf("Error from intermediary with HTTP status code %d %q", statusCode, statusText)
		return twirpErrorFromIntermediary(statusCode, msg, string(respBodyBytes))
	}

	errorCode := twirp.ErrorCode(tj.Code)
	if !twirp.IsValidErrorCode(errorCode) {
		msg := "invalid type returned from server error response: " + tj.Code
		return twirp.InternalError(msg)
	}

	twerr := twirp.NewError(errorCode, tj.Msg)
	for k, v := range tj.Meta {
		twerr = twerr.WithMeta(k, v)
	}
	return twerr
}

// twirpErrorFromIntermediary maps HTTP errors from non-twirp sources to twirp errors.
// The mapping is similar to gRPC: https://github.com/grpc/grpc/blob/master/doc/http-grpc-status-mapping.md.
// Returned twirp Errors have some additional metadata for inspection.
func twirpErrorFromIntermediary(status int, msg string, bodyOrLocation string) twirp.Error {
	var code twirp.ErrorCode
	if isHTTPRedirect(status) { // 3xx
		code = twirp.Internal
	} else {
		switch status {
		case 400: // Bad Request
			code = twirp.Internal
		case 401: // Unauthorized
			code = twirp.Unauthenticated
		case 403: // Forbidden
			code = twirp.PermissionDenied
		case 404: // Not Found
			code = twirp.BadRoute
		case 429, 502, 503, 504: // Too Many Requests, Bad Gateway, Service Unavailable, Gateway Timeout
			code = twirp.Unavailable
		default: // All other codes
			code = twirp.Unknown
		}
	}

	twerr := twirp.NewError(code, msg)
	twerr = twerr.WithMeta("http_error_from_intermediary", "true") // to easily know if this error was from intermediary
	twerr = twerr.WithMeta("status_code", strconv.Itoa(status))
	if isHTTPRedirect(status) {
		twerr = twerr.WithMeta("location", bodyOrLocation)
	} else {
		twerr = twerr.WithMeta("body", bodyOrLocation)
	}
	return twerr
}
func isHTTPRedirect(status int) bool {
	return status >= 300 && status <= 399
}

// wrappedError implements the github.com/pkg/errors.Causer interface, allowing errors to be
// examined for their root cause.
type wrappedError struct {
	msg   string
	cause error
}

func wrapErr(err error, msg string) error { return &wrappedError{msg: msg, cause: err} }
func (e *wrappedError) Cause() error      { return e.cause }
func (e *wrappedError) Error() string     { return e.msg + ": " + e.cause.Error() }

// clientError adds consistency to errors generated in the client
func clientError(desc string, err error) twirp.Error {
	return twirp.InternalErrorWith(wrapErr(err, desc))
}

// badRouteError is used when the twirp server cannot route a request
func badRouteError(msg string, method, url string) twirp.Error {
	err := twirp.NewError(twirp.BadRoute, msg)
	err = err.WithMeta("twirp_invalid_route", method+" "+url)
	return err
}

// The standard library will, by default, redirect requests (including POSTs) if it gets a 302 or
// 303 response, and also 301s in go1.8. It redirects by making a second request, changing the
// method to GET and removing the body. This produces very confusing error messages, so instead we
// set a redirect policy that always errors. This stops Go from executing the redirect.
//
// We have to be a little careful in case the user-provided http.Client has its own CheckRedirect
// policy - if so, we'll run through that policy first.
//
// Because this requires modifying the http.Client, we make a new copy of the client and return it.
func withoutRedirects(in *http.Client) *http.Client {
	copy := *in
	copy.CheckRedirect = func(req *http.Request, via []*http.Request) error {
		if in.CheckRedirect != nil {
			// Run the input's redirect if it exists, in case it has side effects, but ignore any error it
			// returns, since we want to use ErrUseLastResponse.
			err := in.CheckRedirect(req, via)
			_ = err // Silly, but this makes sure generated code passes errcheck -blank, which some people use.
		}
		return http.ErrUseLastResponse
	}
	return &copy
}

// doProtobufRequest is common code to make a request to the remote twirp service.
func doProtobufRequest(ctx context.Context, client HTTPClient, url string, in, out proto.Message) (err error) {
	reqBodyBytes, err := proto.Marshal(in)
	if err != nil {
		return clientError("failed to marshal proto request", err)
	}
	reqBody := bytes.NewBuffer(reqBodyBytes)
	if err = ctx.Err(); err != nil {
		return clientError("aborted because context was done", err)
	}

	req, err := newRequest(ctx, url, reqBody, "application/protobuf")
	if err != nil {
		return clientError("could not build request", err)
	}
	resp, err := client.Do(req)
	if err != nil {
		return clientError("failed to do request", err)
	}

	defer func() {
		cerr := resp.Body.Close()
		if err == nil && cerr != nil {
			err = clientError("failed to close response body", cerr)
		}
	}()

	if err = ctx.Err(); err != nil {
		return clientError("aborted because context was done", err)
	}

	if resp.StatusCode != 200 {
		return errorFromResponse(resp)
	}

	respBodyBytes, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		return clientError("failed to read response body", err)
	}
	if err = ctx.Err(); err != nil {
		return clientError("aborted because context was done", err)
	}

	if err = proto.Unmarshal(respBodyBytes, out); err != nil {
		return clientError("failed to unmarshal proto response", err)
	}
	return nil
}

// doJSONRequest is common code to make a request to the remote twirp service.
func doJSONRequest(ctx context.Context, client HTTPClient, url string, in, out proto.Message) (err error) {
	reqBody := bytes.NewBuffer(nil)
	marshaler := &jsonpb.Marshaler{OrigName: true}
	if err = marshaler.Marshal(reqBody, in); err != nil {
		return clientError("failed to marshal json request", err)
	}
	if err = ctx.Err(); err != nil {
		return clientError("aborted because context was done", err)
	}

	req, err := newRequest(ctx, url, reqBody, "application/json")
	if err != nil {
		return clientError("could not build request", err)
	}
	resp, err := client.Do(req)
	if err != nil {
		return clientError("failed to do request", err)
	}

	defer func() {
		cerr := resp.Body.Close()
		if err == nil && cerr != nil {
			err = clientError("failed to close response body", cerr)
		}
	}()

	if err = ctx.Err(); err != nil {
		return clientError("aborted because context was done", err)
	}

	if resp.StatusCode != 200 {
		return errorFromResponse(resp)
	}

	unmarshaler := jsonpb.Unmarshaler{AllowUnknownFields: true}
	if err = unmarshaler.Unmarshal(resp.Body, out); err != nil {
		return clientError("failed to unmarshal json response", err)
	}
	if err = ctx.Err(); err != nil {
		return clientError("aborted because context was done", err)
	}
	return nil
}

// Call twirp.ServerHooks.RequestReceived if the hook is available
func callRequestReceived(ctx context.Context, h *twirp.ServerHooks) (context.Context, error) {
	if h == nil || h.RequestReceived == nil {
		return ctx, nil
	}
	return h.RequestReceived(ctx)
}

// Call twirp.ServerHooks.RequestRouted if the hook is available
func callRequestRouted(ctx context.Context, h *twirp.ServerHooks) (context.Context, error) {
	if h == nil || h.RequestRouted == nil {
		return ctx, nil
	}
	return h.RequestRouted(ctx)
}

// Call twirp.ServerHooks.ResponsePrepared if the hook is available
func callResponsePrepared(ctx context.Context, h *twirp.ServerHooks) context.Context {
	if h == nil || h.ResponsePrepared == nil {
		return ctx
	}
	return h.ResponsePrepared(ctx)
}

// Call twirp.ServerHooks.ResponseSent if the hook is available
func callResponseSent(ctx context.Context, h *twirp.ServerHooks) {
	if h == nil || h.ResponseSent == nil {
		return
	}
	h.ResponseSent(ctx)
}

// Call twirp.ServerHooks.Error if the hook is available
func callError(ctx context.Context, h *twirp.ServerHooks, err twirp.Error) context.Context {
	if h == nil || h.Error == nil {
		return ctx
	}
	return h.Error(ctx, err)
}

var twirpFileDescriptor0 = []byte{
	// 729 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0x5b, 0x4f, 0xd4, 0x40,
	0x14, 0x4e, 0x61, 0x81, 0xe5, 0xb4, 0xcb, 0xc3, 0x70, 0x49, 0xb3, 0x8a, 0x42, 0x13, 0x13, 0x4c,
	0x0c, 0xea, 0x12, 0x1f, 0xf4, 0xc5, 0x90, 0x18, 0x6f, 0x51, 0x42, 0x0a, 0xf8, 0xba, 0x0e, 0xdd,
	0xd9, 0xa5, 0x61, 0xb7, 0x2d, 0x33, 0x53, 0x64, 0x7d, 0xf7, 0x07, 0xf8, 0xec, 0x9f, 0x35, 0x73,
	0xdb, 0xce, 0x94, 0x62, 0xd0, 0xc8, 0x53, 0xe7, 0x5c, 0xe6, 0x7c, 0x73, 0xbe, 0x99, 0xf3, 0xed,
	0xc2, 0x0a, 0x2b, 0xf8, 0x70, 0x8a, 0x8b, 0x74, 0xb7, 0xa0, 0x39, 0xcf, 0x51, 0xdb, 0xd8, 0xd1,
	0x36, 0xf8, 0x1f, 0xb2, 0x61, 0x1e, 0x93, 0x8b, 0x92, 0x30, 0x8e, 0x10, 0xb4, 0x58, 0x49, 0xd3,
	0xd0, 0xdb, 0xf2, 0x76, 0x96, 0x63, 0xb9, 0x8e, 0x7e, 0x7a, 0x10, 0xa8, 0x1c, 0x56, 0xe4, 0x19,
	0x23, 0x68, 0x1b, 0x82, 0x41, 0xca, 0x8a, 0x31, 0x9e, 0xf6, 0x33, 0x3c, 0x21, 0x3a, 0xd9, 0xd7,
	0xbe, 0x03, 0x3c, 0x21, 0x68, 0x0d, 0x16, 0xc8, 0x04, 0xa7, 0xe3, 0x70, 0x4e, 0xc6, 0x94, 0x21,
	0x36, 0x26, 0x25, 0xa5, 0x24, 0xe3, 0x7d, 0x96, 0x67, 0xa3, 0x70, 0x5e, 0x6d, 0xd4, 0xbe, 0xa3,
	0x3c, 0x1b, 0xa1, 0x47, 0xb0, 0xc2, 0x08, 0xbd, 0x24, 0xb4, 0x7f, 0x49, 0x28, 0x4b, 0xf3, 0x2c,
	0x6c, 0xc9, 0xa4, 0x8e, 0xf2, 0x7e, 0x51, 0xce, 0xe8, 0x35, 0xf8, 0xfb, 0x25, 0x3f, 0x33, 0xc7,
	0x9e, 0xc1, 0x79, 0x36, 0x5c, 0x17, 0xda, 0x05, 0x66, 0xec, 0x5b, 0x4e, 0x07, 0xf2, 0x1c, 0x41,
	0x3c, 0xb3, 0xa3, 0xe7, 0x10, 0xa8, 0x02, 0x55, 0x4f, 0x38, 0x49, 0x08, 0x63, 0x7d, 0x9e, 0x9f,
	0x93, 0xcc, 0xf4, 0xa4, 0x7c, 0xc7, 0xc2, 0x15, 0x3d, 0x86, 0xd5, 0xc3, 0x31, 0x9e, 0x9e, 0xe2,
	0xe4, 0xfc, 0x80, 0x5c, 0x71, 0x8b, 0xb2, 0x8c, 0x5c, 0x71, 0x43, 0x99, 0x58, 0x47, 0x7b, 0xb0,
	0xe6, 0xa6, 0x6a, 0x94, 0x7b, 0xb0, 0xcc, 0x29, 0x4e, 0xce, 0xfb, 0x15, 0xc7, 0x6d, 0xe9, 0x38,
	0xa1, 0x69, 0xf4, 0xb6, 0xaa, 0x2f, 0xbe, 0x56, 0x7d, 0x41, 0xab, 0x4c, 0x6f, 0xc7, 0x72, 0xed,
	0xd6, 0x99, 0xab, 0xd5, 0x79, 0x59, 0x81, 0xab, 0x3a, 0x55, 0x8b, 0x85, 0xf6, 0xf7, 0x4b, 0x6a,
	0xb8, 0xf2, 0x8d, 0xef, 0x84, 0x8e, 0xa3, 0x27, 0xd6, 0x56, 0x5c, 0x32, 0x62, 0xf1, 0x5b, 0x08,
	0x5b, 0x1f, 0x42, 0x19, 0xd1, 0x2b, 0x58, 0xaf, 0x65, 0xdf, 0x1e, 0xe9, 0x2b, 0xa0, 0x63, 0x71,
	0xe0, 0x23, 0x82, 0x69, 0x62, 0xdf, 0xe3, 0x45, 0x49, 0xe8, 0xd4, 0xdc, 0xa3, 0x34, 0xd4, 0x3d,
	0x8e, 0x08, 0x4b, 0xbf, 0x13, 0xd9, 0x6c, 0x27, 0x9e, 0xd9, 0x28, 0x84, 0x25, 0xb1, 0xce, 0xca,
	0x89, 0x7c, 0x4d, 0x9d, 0xd8, 0x98, 0x82, 0x4e, 0x07, 0x41, 0x9f, 0xed, 0x29, 0x2c, 0x51, 0xc2,
	0xca, 0x31, 0x67, 0xa1, 0xb7, 0x35, 0xbf, 0xe3, 0xf7, 0xd6, 0x77, 0x67, 0xc3, 0x21, 0xf3, 0x63,
	0x19, 0x8d, 0x4d, 0x56, 0xf4, 0xcb, 0x03, 0xdf, 0x0a, 0x34, 0x8d, 0x88, 0x7c, 0x03, 0x62, 0x12,
	0xe6, 0xf4, 0x1b, 0x10, 0x23, 0xb0, 0x01, 0x8b, 0x98, 0xf2, 0x94, 0x71, 0xfd, 0xcc, 0xb5, 0x25,
	0x7a, 0xc4, 0xe3, 0xd3, 0x72, 0xa2, 0x1f, 0xb6, 0x32, 0x44, 0x8f, 0xac, 0x18, 0xf2, 0x29, 0xc7,
	0xa3, 0x70, 0x41, 0x5d, 0xa8, 0xb1, 0x45, 0x6c, 0x42, 0x38, 0x1e, 0x60, 0x8e, 0xc3, 0x45, 0xf5,
	0x8e, 0x8d, 0x2d, 0x78, 0xdc, 0x17, 0x05, 0xee, 0x8e, 0xc7, 0x77, 0xb0, 0xea, 0x20, 0x68, 0x1e,
	0x9f, 0xd5, 0x79, 0xdc, 0xa8, 0x78, 0xdc, 0x97, 0x9d, 0xd6, 0x89, 0xfc, 0xe1, 0x81, 0x2f, 0x2b,
	0xfd, 0x27, 0x22, 0x25, 0x65, 0x7c, 0x28, 0x29, 0x6b, 0x19, 0xca, 0x94, 0xed, 0x50, 0xb6, 0x50,
	0xa3, 0x0c, 0xc3, 0xaa, 0x3a, 0xe0, 0xdd, 0x71, 0xf6, 0x1e, 0xd6, 0x5c, 0x88, 0x7f, 0x26, 0x2d,
	0x83, 0xc0, 0x0e, 0xdc, 0x9a, 0x34, 0x9b, 0x9c, 0xf9, 0x3f, 0x90, 0xd3, 0x72, 0xc9, 0xe9, 0xbd,
	0x51, 0xbf, 0x07, 0x47, 0x84, 0x5e, 0xa6, 0x09, 0x41, 0x2f, 0xa0, 0x25, 0x4c, 0x64, 0x0d, 0x89,
	0xf5, 0x73, 0xd1, 0xdd, 0xa8, 0xbb, 0x55, 0x9f, 0xa2, 0x8a, 0x50, 0x57, 0xab, 0x8a, 0x30, 0xed,
	0x2a, 0x96, 0x7a, 0xdb, 0x55, 0x6c, 0x4d, 0xee, 0x0d, 0x5c, 0xc1, 0x35, 0xd5, 0x3e, 0x43, 0x60,
	0xbb, 0xd1, 0x66, 0xb5, 0xbd, 0x41, 0x9f, 0xbb, 0x0f, 0x6e, 0x0a, 0x5f, 0x47, 0x11, 0xdf, 0x06,
	0x14, 0xf1, 0x6d, 0x42, 0xb1, 0x54, 0xba, 0x09, 0xc5, 0x16, 0xdf, 0xde, 0x59, 0x4d, 0x59, 0x0d,
	0xcc, 0x21, 0x74, 0x1c, 0x3f, 0x6a, 0x2a, 0x64, 0x49, 0x71, 0xf7, 0xe1, 0x8d, 0x71, 0x8d, 0xe4,
	0x2a, 0xab, 0xc1, 0xf9, 0x08, 0xbe, 0x72, 0xc8, 0x18, 0xba, 0x5f, 0x13, 0x3d, 0x67, 0x14, 0xba,
	0x9b, 0x37, 0x44, 0x2b, 0x04, 0x4b, 0x11, 0xae, 0x21, 0xc8, 0x98, 0x8d, 0x70, 0x5d, 0xa0, 0x6c,
	0x84, 0x06, 0x71, 0xe9, 0x25, 0xee, 0x88, 0x1a, 0x88, 0x4f, 0x10, 0x68, 0x08, 0xa5, 0x00, 0x9b,
	0xf5, 0xe9, 0xf9, 0x1b, 0x90, 0xd3, 0x45, 0xf9, 0x5f, 0x68, 0xef, 0x77, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x8f, 0x34, 0xef, 0xcd, 0x1d, 0x09, 0x00, 0x00,
}
